### ISSUE TITLE
tag is needed when pushing to registry

### ISSUE THREAD

**Issue by balazssoltesz** [nx-tools/nx-tools#362]
hello, i installed @nx-tools/nx-docker  & @nx-tools/docker-metadata packages. 
i have a target with the following configuration:

```
        "docker": {
          "executor": "@nx-tools/nx-docker:build",
          "options": {
            "file": "apps/admin/Dockerfile",
            "push": true,
            "metadata": {
              "images": ["#########"],
              "tags": [
                  "type=match,pattern=admin@(.*),group=1"
              ] 
            }
          },
          "dependsOn": [
            {
              "target": "build",
              "projects": "self"
            }
          ]
        },
```

Then i added tag "admin@0.1.0" to my last commit, but when i try to run this target, i get the error message:   tag is needed when pushing to registry,

Am i doing somthing wrong?

**Comment by gperdomor** [comment]
Hi @balazssoltesz, the config seems to be fine... Are you running the builder in your local machine or in a supported CI environment

**Comment by DaSchTour** [comment]
I have a similar issue. My setup was working with version 1 but is now broken with version 2.

**Comment by gperdomor** [comment]
@DaSchTour for v2 should be:

```
"executor": "@nx-tools/nx-docker:build",
  "options": {
    "push": true,
    "file": "apps/…/Dockerfile",
    "metadata": {
      "tags": ["type=ref,event=branch"],
      "images": ["…"]
  }
}
```

`meta`renamed to `metadata`... and remove `meta.enabled` prop

If still having issues please provide a minimum reproduction repository

**Comment by DaSchTour** [comment]
I updated my configuration to this
```
"docker": {
      "executor": "@nx-tools/nx-docker:build",
      "options": {
        "push": true,
        "file": "apps/…/Dockerfile",
        "metadata": {
          "tags": [
            "type=schedule",
            "type=ref,event=branch",
            "type=ref,event=tag",
            "type=ref,event=pr",
            "type=semver,pattern={{version}}",
            "type=semver,pattern={{major}}.{{minor}}",
            "type=semver,pattern={{major}}",
            "type=sha,prefix=sha-"
          ],
          "images": […]
        }
      }
    },
```

My CI fails with
```
error: tag is needed when pushing to registry
buildx failed with: error: tag is needed when pushing to registry
```

**Comment by DaSchTour** [comment]
I had to fix my package-lock and now it actually works. Thanks for the help @gperdomor

**Comment by NexZhu** [comment]
@DaSchTour Hello, I encountered the same problem, what does it have to do with package-lock? Could you explain please?
