### ISSUE TITLE
(nx-docker) Update peer dependency to dotenv

### ISSUE THREAD

**Issue by chromey** [nx-tools/nx-tools#457]
Hi,

the peer dependency to `dotenv` is currently restricted  to `^10.0.0`. However, the package went through six major releases since January (the reasons are addressed in this issue: https://github.com/motdotla/dotenv/issues/616).

Would you consider relaxing the version restriction to something more lenient or, depending on the level of integration, even completely remove the upper bound?

**Comment by gperdomor** [comment]
@chromey try 3.0.0-alpha.1 😄

**Comment by chromey** [comment]
Works like a charm btw ;) Thx!
