### ISSUE TITLE
Major release is missing release notes

### ISSUE THREAD

**Issue by oguera** [nx-tools/nx-tools#556]
Hi @gperdomor !

I saw that there is a new major release but couldn't find any release notes about what changed, if there are breaking changes etc.

Is there any information about that?

Cheers ✌️

**Comment by gperdomor** [comment]
@oguera Hi, this release focused in update the project to nx 14 and uses the swc compiler, please check the changelog https://github.com/nx-tools/nx-tools/blob/main/packages/nx-docker/CHANGELOG.md

Should be safe to update from version 2 to 3...

**Comment by oguera** [comment]
Thank you for the hint! Totally overlooked the CHANGELOG.md 👍
