### ISSUE TITLE
Include chalk dependency in package.json

### ISSUE THREAD

**Issue by patdx** [nx-tools/nx-tools#583]
Nx-docker and nx-core seem to use chalk dependency, but they only support v4, not v5 (ES module version) and it is not specified in their package json files. So if the root project has chalk v5 installed, it can cause an error like this:

```
$ nx docker my-app

> nx run my-app:docker


 >  NX   require() of ES Module /home/pm/my-app/node_modules/chalk/source/index.js from /home/pm/my-app/node_modules/@nx-tools/core/src/lib/logging.js not supported.

   Instead change the require of index.js in /home/pm/my-app/node_modules/@nx-tools/core/src/lib/logging.js to a dynamic import() which is available in all CommonJS modules.
   Pass --verbose to see the stacktrace.


 ————————————————————————————————————————————————————————————————————————
 >  NX   Ran target docker for project my-app (287ms)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

For example, here is a snippet of the [package.json of nx-docker v3.0.0](https://unpkg.com/browse/@nx-tools/nx-docker@3.0.0/package.json):

```
  "dependencies": {
    "@nx-tools/core": "^3.0.0",
    "@swc/helpers": "^0.3.17",
    "csv-parse": "^4.16.3",
    "semver": "^7.3.7",
    "tmp": "^0.2.1"
  },
  "optionalDependencies": {
    "@nx-tools/docker-metadata": "^3.0.0"
  },
  "peerDependencies": {
    "dotenv": ">=10.0.0",
    "tslib": "^2.1.0"
  },
```

How to fix:

Make sure chalk v4 is specified in the built package json files eg:

```diff
  "dependencies": {
    "@nx-tools/core": "^3.0.0",
    "@swc/helpers": "^0.3.17",
    "csv-parse": "^4.16.3",
    "semver": "^7.3.7",
    "tmp": "^0.2.1"
+   "chalk": "4"
  },
```

Since I am using Yarn Berry in the repo where I had this error, I was able to fix it by using the [packageExtensions option in .yarnrc.yml](https://yarnpkg.com/configuration/yarnrc#packageExtensions) to insert the dependency:

```yaml
# .yarnrc.yml
packageExtensions:
  '@nx-tools/nx-docker@*':
    dependencies:
      chalk: '^4'
  '@nx-tools/core@*':
    dependencies:
      chalk: '^4'
```

Note that I am using yarn berry in node-modules mode, which is basically an npm compatibility mode. It is not the (more controversial) yarn PnP mode. To the best of my knowledge this issue could affect npm, pnpm and yarn equally.

**Comment by gperdomor** [comment]
Solven in 3.0.1...

**Comment by gperdomor** [comment]
Thanks @patdx
